AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Data Platform SRE Simulator: Medallion S3 Storage'

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'data-platform-raw-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  SilverDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'data-platform-silver-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  GoldDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'data-platform-gold-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled