name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-aws-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure.yml \
            --stack-name data-platform-storage-stack \
            --capabilities CAPABILITY_NAMED_IAM
# --- IAM GROUPS & USERS ---
  
  DETeamGroup:
    Type: AWS::IAM::Group

  DatabricksServiceUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref DETeamGroup

  # --- IAM POLICIES ---

  DETeamS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DETeamS3ReadWrite
      Groups:
        - !Ref DETeamGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !GetAtt RawDataBucket.Arn
              - !Sub "${RawDataBucket.Arn}/*"
              - !GetAtt SilverDataBucket.Arn
              - !Sub "${SilverDataBucket.Arn}/*"
              - !GetAtt GoldDataBucket.Arn
              - !Sub "${GoldDataBucket.Arn}/*"